title: 'elgchat.github.io'
description: "A man who likes his freedom."
baseurl: "/"
url: "http://www.vimor.cn"

header_pages:
  - index.md
#   - about.md
  - contact.md

style: dark

footer: 'follow us on <a href="https://github.com/vimor-cn/">gitHub</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
